import type { Product, Category, FAQItem, StoreLocation } from '@/types';

export const CATEGORY_META: Record<string, { gradient: [string, string]; icon: string }> = {
  bags:        { gradient: ['#6B4A18', '#C9A96E'], icon: 'ShoppingBag' },
  shoes:       { gradient: ['#7A2E2E', '#C96E6E'], icon: 'Footprints' },
  watches:     { gradient: ['#1C120A', '#4A3525'], icon: 'Watch' },
  belts:       { gradient: ['#3D2A1A', '#8B7355'], icon: 'CircleDot' },
  bracelets:   { gradient: ['#8B5E1A', '#E0C07A'], icon: 'Gem' },
  hats:        { gradient: ['#1A3A2A', '#3D7A5A'], icon: 'Crown' },
  jewelry:     { gradient: ['#5A1A5A', '#A060A0'], icon: 'Sparkles' },
  sunglasses:  { gradient: ['#1A1A3A', '#3A4A7A'], icon: 'Glasses' },
  scarves:     { gradient: ['#4A1A3A', '#8B4A75'], icon: 'Wind' },
  wallets:     { gradient: ['#1A3A1A', '#3A6B3A'], icon: 'Wallet' },
  perfumes:    { gradient: ['#3A1A4A', '#7A4A8B'], icon: 'Droplets' },
  clothing:    { gradient: ['#2A2A2A', '#5A5A6A'], icon: 'Shirt' },
  keychains:   { gradient: ['#4A2A1A', '#8B5A3A'], icon: 'Key' },
  hair:        { gradient: ['#3A1A1A', '#7A3A4A'], icon: 'Scissors' },
  luggage:     { gradient: ['#1A2A3A', '#3A5A7A'], icon: 'Briefcase' },
};

export const categories: Category[] = [
  { id: 'bags',       name: { fr: 'Sacs',                   en: 'Bags' },            image: '/images/01_bags_champagne_gold_beige_cream.jpg' },
  { id: 'shoes',      name: { fr: 'Chaussures',             en: 'Shoes' },           image: '/images/02_shoes_matte_black_matte_white.jpg' },
  { id: 'watches',    name: { fr: 'Montres',                en: 'Watches' },         image: '/images/03_watches_burgundy_champagne_gold.jpg' },
  { id: 'jewelry',    name: { fr: 'Bijoux',                 en: 'Jewelry' },         image: '/images/04_jewelry_emerald_green_warm_nude.jpg' },
  { id: 'bracelets',  name: { fr: 'Bracelets',              en: 'Bracelets' },       image: '/images/05_bracelets_ivory_white_soft_gray.jpg' },
  { id: 'belts',      name: { fr: 'Ceintures',              en: 'Belts' },           image: '/images/06_belts_rose_gold_coffee_brown.jpg' },
  { id: 'hats',       name: { fr: 'Chapeaux & Bonnets',     en: 'Hats & Beanies' }, image: '/images/07_hats_nude_beige_marble_white.jpg' },
  { id: 'sunglasses', name: { fr: 'Lunettes de Soleil',     en: 'Sunglasses' },      image: '/images/08_sunglasses_royal_purple_matte_black.jpg' },
  { id: 'scarves',    name: { fr: 'Écharpes & Foulards',    en: 'Scarves' },         image: '/images/09_scarves_dusty_pink_ivory.jpg' },
  { id: 'wallets',    name: { fr: 'Portefeuilles',          en: 'Wallets' },         image: '/images/10_wallets_chocolate_brown_sand_beige.jpg' },
  { id: 'perfumes',   name: { fr: 'Parfums',                en: 'Perfumes' },        image: '/images/11_perfumes_navy_blue_taupe.jpg' },
  { id: 'clothing',   name: { fr: 'Vêtements',              en: 'Clothing' },        image: '/images/12_clothing_camel_caramel_blush_pink.jpg' },
  { id: 'keychains',  name: { fr: 'Porte-clés & Bijoux de Sac', en: 'Keychains & Bag Charms' }, image: '/images/13_keychains_metallic_silver_olive_green.jpg' },
  { id: 'hair',       name: { fr: 'Accessoires Cheveux',    en: 'Hair Accessories' }, image: '/images/14_hair_accessories_pearl_white_walnut_wood.jpg' },
  { id: 'luggage',    name: { fr: 'Valises & Bagages',      en: 'Luggage & Travel' }, image: '/images/15_luggage_sapphire_blue_metallic_gold.jpg' },
];

export const products: Product[] = [
  // Trending
  {
    id: 'venice-bag',
    name: { fr: 'Sac à main Venice', en: 'Venice Handbag' },
    description: { fr: 'Sac à main en cuir luxe avec fermoir doré. Un classique intemporel.', en: 'Luxury leather handbag with gold clasp. A timeless classic.' },
    price: 45000,
    image: '/images/prod-venice.jpg',
    category: 'bags',
    badges: ['trending'],
    inStock: true,
    store: 'both',
  },
  {
    id: 'elegance-sneakers',
    name: { fr: 'Sneakers Élégance', en: 'Élégance Sneakers' },
    description: { fr: 'Baskets blanches design avec accents dorés.', en: 'White designer sneakers with gold accents.' },
    price: 35000,
    image: '/images/prod-elegance.jpg',
    category: 'shoes',
    badges: ['trending'],
    inStock: true,
    store: 'both',
  },
  {
    id: 'rosee-watch',
    name: { fr: 'Montre Rosée', en: 'Rosée Watch' },
    description: { fr: 'Montre femme en or rose avec cadran rose.', en: 'Rose gold women\'s watch with pink dial.' },
    price: 28000,
    image: '/images/prod-rosee.jpg',
    category: 'watches',
    badges: ['trending'],
    inStock: true,
    store: 'both',
  },
  {
    id: 'premium-belt',
    name: { fr: 'Ceinture Premium', en: 'Premium Belt' },
    description: { fr: 'Ceinture en cuir tressé avec boucle dorée.', en: 'Braided leather belt with gold buckle.' },
    price: 15000,
    image: '/images/prod-premium-belt.jpg',
    category: 'belts',
    badges: ['trending'],
    inStock: true,
    store: 'both',
  },
  // Best sellers
  {
    id: 'luxe-crossbody',
    name: { fr: 'Sac Bandoulière Luxe', en: 'Luxe Crossbody' },
    description: { fr: 'Sac bandoulière en cuir cognac avec chaîne dorée.', en: 'Cognac leather crossbody with gold chain.' },
    price: 38000,
    image: '/images/prod-luxe-crossbody.jpg',
    category: 'bags',
    badges: [],
    inStock: true,
    store: 'both',
  },
  {
    id: 'classic-shoes',
    name: { fr: 'Chaussures Classique', en: 'Classic Shoes' },
    description: { fr: 'Escarpins en cuir noir élégant.', en: 'Elegant black leather pumps.' },
    price: 42000,
    image: '/images/prod-classic-shoes.jpg',
    category: 'shoes',
    badges: [],
    inStock: true,
    store: 'both',
  },
  {
    id: 'gold-cap',
    name: { fr: 'Casquette Édition Or', en: 'Gold Edition Cap' },
    description: { fr: 'Casquette brodée noire avec fil doré.', en: 'Black embroidered cap with gold thread.' },
    price: 12000,
    image: '/images/prod-gold-cap.jpg',
    category: 'hats',
    badges: [],
    inStock: true,
    store: 'yaounde',
  },
  {
    id: 'eternite-watch',
    name: { fr: "Montre Éternité", en: 'Éternité Watch' },
    description: { fr: "Montre classique avec cadran nacre.", en: 'Classic watch with mother-of-pearl dial.' },
    price: 55000,
    image: '/images/prod-eternite-watch.jpg',
    category: 'watches',
    badges: [],
    inStock: true,
    store: 'both',
  },
  // New arrivals
  {
    id: 'tote-bag',
    name: { fr: 'Sac Fourre-tout Élégance', en: 'Élégance Tote' },
    description: { fr: 'Grand sac fourre-tout en cuir camel.', en: 'Large camel leather tote bag.' },
    price: 52000,
    image: '/images/prod-tote.jpg',
    category: 'bags',
    badges: ['new'],
    inStock: true,
    store: 'both',
  },
  {
    id: 'ankle-boots',
    name: { fr: 'Bottines Tendance', en: 'Trendy Ankle Boots' },
    description: { fr: 'Bottines en cuir noir avec talon moderne.', en: 'Black leather ankle boots with modern heel.' },
    price: 48000,
    image: '/images/prod-ankle-boots.jpg',
    category: 'shoes',
    badges: ['new'],
    inStock: true,
    store: 'kribi',
  },
  {
    id: 'winter-beanie',
    name: { fr: 'Bonnet Hiver Premium', en: 'Premium Winter Beanie' },
    description: { fr: 'Bonnet cachemire crème avec patch cuir.', en: 'Cashmere beanie in cream with leather patch.' },
    price: 8000,
    image: '/images/prod-winter-beanie.jpg',
    category: 'hats',
    badges: ['new'],
    inStock: true,
    store: 'both',
  },
  {
    id: 'rose-bracelet',
    name: { fr: 'Bracelet Or Rose', en: 'Rose Gold Bracelet' },
    description: { fr: 'Bracelet chaîne or rose avec charm cœur.', en: 'Rose gold chain bracelet with heart charm.' },
    price: 18000,
    image: '/images/prod-rose-bracelet.jpg',
    category: 'bracelets',
    badges: ['new'],
    inStock: true,
    store: 'yaounde',
  },
  // Sold products
  {
    id: 'vintage-bag',
    name: { fr: 'Sac Vintage Exclusive', en: 'Exclusive Vintage Bag' },
    description: { fr: 'Sac vintage en cuir bordeaux avec fermoir antique.', en: 'Vintage burgundy leather bag with antique clasp.' },
    price: 65000,
    image: '/images/prod-vintage-bag.jpg',
    category: 'bags',
    badges: ['sold'],
    inStock: false,
    store: 'yaounde',
  },
  {
    id: 'gold-sandals',
    name: { fr: 'Sandales Designer', en: 'Designer Sandals' },
    description: { fr: 'Sandales dorées à brides métalliques.', en: 'Metallic gold strappy sandals.' },
    price: 38000,
    image: '/images/prod-gold-sandals.jpg',
    category: 'shoes',
    badges: ['sold'],
    inStock: false,
    store: 'kribi',
  },
  {
    id: 'couture-hat',
    name: { fr: 'Chapeau Haute Couture', en: 'Haute Couture Hat' },
    description: { fr: 'Chapeau à large bord en feutre noir avec ruban soie.', en: 'Wide-brim black felt hat with silk ribbon.' },
    price: 22000,
    image: '/images/prod-couture-hat.jpg',
    category: 'hats',
    badges: ['sold'],
    inStock: false,
    store: 'yaounde',
  },
  {
    id: 'diamond-watch',
    name: { fr: 'Montre Diamant', en: 'Diamond Watch' },
    description: { fr: 'Montre luxe avec lunette sertie de diamants.', en: 'Luxury watch with diamond-encrusted bezel.' },
    price: 120000,
    image: '/images/prod-diamond-watch.jpg',
    category: 'watches',
    badges: ['sold'],
    inStock: false,
    store: 'yaounde',
  },
  // Premium
  {
    id: 'signature-quest',
    name: { fr: 'Sac Signature Quest', en: 'Signature Quest Bag' },
    description: { fr: 'Notre sac phare en cuir noir lisse avec monogramme doré.', en: 'Our flagship bag in smooth black leather with gold monogram.' },
    price: 95000,
    image: '/images/prod-signature.jpg',
    category: 'bags',
    badges: ['premium'],
    inStock: true,
    store: 'yaounde',
  },
  {
    id: 'velvet-heels',
    name: { fr: 'Escarpins Velours', en: 'Velvet Heels' },
    description: { fr: 'Escarpins en velours bordeaux avec talon doré.', en: 'Burgundy velvet pumps with gold heel.' },
    price: 58000,
    image: '/images/prod-velvet-heels.jpg',
    category: 'shoes',
    badges: ['premium'],
    inStock: true,
    store: 'both',
  },
  {
    id: 'sapphire-watch',
    name: { fr: 'Montre Saphir', en: 'Sapphire Watch' },
    description: { fr: 'Montre avec cadran cristal saphir bleu et boîtier doré.', en: 'Watch with blue sapphire crystal dial and gold case.' },
    price: 85000,
    image: '/images/prod-sapphire-watch.jpg',
    category: 'watches',
    badges: ['premium'],
    inStock: true,
    store: 'yaounde',
  },
  {
    id: 'croc-belt',
    name: { fr: 'Ceinture Crocodile', en: 'Crocodile Belt' },
    description: { fr: 'Ceinture en cuir façon crocodile avec boucle dorée brossée.', en: 'Crocodile-embossed leather belt with brushed gold buckle.' },
    price: 45000,
    image: '/images/prod-croc-belt.jpg',
    category: 'belts',
    badges: ['premium'],
    inStock: true,
    store: 'both',
  },
];

export const faqItems: FAQItem[] = [
  {
    question: { fr: 'Cet article est-il encore disponible ?', en: 'Is this item still available?' },
    answer: { fr: 'Oui/Non selon le stock disponible. Contactez-nous pour vérifier.', en: 'Yes/No depending on available stock. Contact us to verify.' },
  },
  {
    question: { fr: "Est-il possible de payer à la livraison ?", en: 'Is cash on delivery available?' },
    answer: { fr: 'Non, le paiement doit être effectué avant l\'expédition ou la livraison.', en: 'No, payment must be made before shipping or delivery.' },
  },
  {
    question: { fr: 'Puis-je retourner un article ?', en: 'Can I return an item?' },
    answer: { fr: 'Non, les retours ne sont pas acceptés.', en: 'No, returns are not accepted.' },
  },
  {
    question: { fr: "Avez-vous d'autres couleurs ?", en: 'Do you have other colors?' },
    answer: { fr: 'Oui/Non selon les modèles disponibles.', en: 'Yes/No depending on available models.' },
  },
  {
    question: { fr: 'Avez-vous des grandes pointures ?', en: 'Do you have large sizes?' },
    answer: { fr: 'Oui/Non selon les arrivages.', en: 'Yes/No depending on new arrivals.' },
  },
  {
    question: { fr: 'Effectuez-vous des livraisons ?', en: 'Do you offer delivery?' },
    answer: { fr: 'Oui, nous livrons dans plusieurs zones.', en: 'Yes, we deliver to multiple locations.' },
  },
  {
    question: { fr: 'Prenez-vous des avances ?', en: 'Do you accept advance payments?' },
    answer: { fr: 'Oui. Vous payez la moitié et disposez de 7 jours pour compléter. Passé ce délai, l\'article est remis en vente et l\'avance n\'est pas remboursable.', en: 'Yes. You pay half and have 7 days to complete payment. After this period, the item is put back on sale and the deposit is not refundable.' },
  },
  {
    question: { fr: 'Où êtes-vous situés ?', en: 'Where are you located?' },
    answer: { fr: "Yaoundé : Entre l'agence United et la boulangerie Select. Kribi : Dombe, 2ème route, face les brasseries, immeuble blanc jaune à côté de la cave de Guyso.", en: 'Yaoundé: Between United Travel Agency and Select Bakery. Kribi: Dombe, 2nd road, opposite the brasseries, yellow-white building next to the Guyso cave.' },
  },
  {
    question: { fr: 'Combien coûtent les livraisons ?', en: 'How much does delivery cost?' },
    answer: { fr: "Les frais commencent à partir de 1000 FCFA selon votre localisation.", en: 'Fees start from 1000 FCFA depending on your location.' },
  },
  {
    question: { fr: 'Comment payer ?', en: 'How can I pay?' },
    answer: { fr: 'Orange Money (695165425), Mobile Money (672714400) au nom de Michelle Ngassa, ou en espèces.', en: 'Orange Money (695165425), Mobile Money (672714400) to Michelle Ngassa, or cash.' },
  },
];

export const storeLocations: StoreLocation[] = [
  {
    id: 'yaounde',
    name: { fr: 'Yaoundé', en: 'Yaoundé' },
    address: { fr: "Entre l'agence de voyage United et la boulangerie Select, avant la montée Hôpital de la Caisse", en: 'Between United Travel Agency and Select Bakery, before the road to Hôpital de la Caisse' },
    whatsapp: '237672714400',
  },
  {
    id: 'kribi',
    name: { fr: 'Kribi', en: 'Kribi' },
    address: { fr: "Dombe, 2ème route, face les brasseries, immeuble blanc jaune à côté de la cave de Guyso", en: 'Dombe, 2nd road, opposite the brasseries, yellow-white building next to the Guyso cave' },
    whatsapp: '237695165425',
  },
];

export const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      products: 'Produits',
      about: 'À propos',
      contact: 'Contact',
      search: 'Rechercher',
      cart: 'Panier',
    },
    hero: {
      caption: 'BOUTIQUE EN LIGNE',
      headline: "Le chic n'a jamais été aussi audacieux.",
      subtitle: "Sacs, chaussures, montres et accessoires de luxe. Livraison express à Yaoundé, Kribi et bien plus.",
      ctaPrimary: 'Acheter maintenant',
      ctaSecondary: 'Explorer la collection',
      scroll: 'Scroll',
    },
    about: {
      caption: 'NOTRE HISTOIRE',
      headline: "L'élégance rencontre l'audace",
      body: "Chez Guest Store, nous croyons que chaque femme mérite de se sentir exceptionnelle. Notre boutique à Yaoundé — Essos, United-Select, et notre adresse à Kribi — Dombe 2ème route face les brasseries, immeuble blanc jaune à côté de la cave de Guyso, vous offrent une sélection pointue de sacs, chaussures, montres et accessoires premium. Tout « BY MICH'AM ».",
      cta: 'Découvrir nos produits',
    },
    categories: {
      caption: 'NOS UNIVERS',
      headline: 'Explorez nos catégories',
      all: 'Tout voir',
      browse: 'Parcourir',
      items: 'articles',
    },
    trending: {
      caption: 'SÉLECTIONNÉS POUR VOUS',
      headline: 'Tendances du moment',
      seeAll: 'Voir tout',
    },
    bestSellers: {
      caption: 'LES PLUS AIMÉS',
      headline: 'Meilleures ventes',
    },
    newArrivals: {
      caption: 'FRAÎCHEMENT ARRIVÉS',
      headline: 'Nouveaux arrivages',
    },
    soldProducts: {
      caption: 'ÉDITIONS LIMITÉES',
      headline: 'Produits vendus',
      soldOut: 'ÉPUISÉ',
      popup: 'Ce produit est épuisé. Contactez-nous pour les nouveaux arrivages.',
    },
    premium: {
      caption: 'COLLECTION PREMIUM',
      headline: 'Styles premium',
    },
    search: {
      headline: 'Que recherchez-vous ?',
      placeholder: 'Rechercher un produit...',
      voice: 'Recherche vocale',
      tags: ['Sacs', 'Montres', 'Chaussures', 'Nouveautés'],
    },
    location: {
      caption: 'NOS BOUTIQUES',
      headline: 'Trouvez-nous près de chez vous',
      selectStore: 'Sélectionnez votre boutique pour commander',
      whatsapp: 'WhatsApp',
    },
    faq: {
      caption: 'QUESTIONS FRÉQUENTES',
      headline: 'FAQ',
    },
    product: {
      inStock: 'En stock',
      outOfStock: 'Épuisé',
      orderWhatsapp: 'Commander sur WhatsApp',
      addToCart: 'Ajouter au panier',
      addFavorites: 'Ajouter aux favoris',
      similar: 'Produits similaires',
      selectStore: 'Choisir la boutique',
      yaounde: 'Yaoundé',
      kribi: 'Kribi',
    },
    cart: {
      title: 'Votre panier',
      empty: 'Votre panier est vide',
      discover: 'Découvrir les produits',
      subtotal: 'Sous-total',
      checkout: 'Passer la commande',
      continue: 'Continuer les achats',
    },
    footer: {
      tagline: "L'élégance n'a pas de prix. Le style, si.",
      navigation: 'Navigation',
      contact: 'Contact',
      followUs: 'Suivez-nous',
      rights: 'Tous droits réservés.',
      admin: 'Mode administrateur',
    },
    badges: {
      trending: 'Tendance',
      new: 'Nouveau',
      premium: 'Premium',
      sold: 'Vendu',
    },
    currency: 'FCFA',
  },
  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      about: 'About',
      contact: 'Contact',
      search: 'Search',
      cart: 'Cart',
    },
    hero: {
      caption: 'ONLINE BOUTIQUE',
      headline: 'Chic has never been this bold.',
      subtitle: 'Bags, shoes, watches, and luxury accessories. Express delivery in Yaoundé, Kribi, and beyond.',
      ctaPrimary: 'Shop now',
      ctaSecondary: 'Explore collection',
      scroll: 'Scroll',
    },
    about: {
      caption: 'OUR STORY',
      headline: 'Where elegance meets boldness',
      body: "At Guest Store, we believe every woman deserves to feel exceptional. Our boutique at Yaoundé — Essos, United-Select and our Kribi location — Dombe 2ème route face les brasseries, immeuble blanc jaune à côté de la cave de Guyso, offer you a curated selection of bags, shoes, watches, and premium accessories. All \"BY MICH'AM\".",
      cta: 'Discover our products',
    },
    categories: {
      caption: 'OUR WORLDS',
      headline: 'Explore our categories',
      all: 'See all',
      browse: 'Browse',
      items: 'items',
    },
    trending: {
      caption: 'SELECTED FOR YOU',
      headline: 'Trending now',
      seeAll: 'See all',
    },
    bestSellers: {
      caption: 'MOST LOVED',
      headline: 'Best sellers',
    },
    newArrivals: {
      caption: 'FRESHLY ARRIVED',
      headline: 'New arrivals',
    },
    soldProducts: {
      caption: 'LIMITED EDITIONS',
      headline: 'Sold out',
      soldOut: 'SOLD OUT',
      popup: 'This product is sold out. Contact us for new arrivals.',
    },
    premium: {
      caption: 'PREMIUM COLLECTION',
      headline: 'Premium styles',
    },
    search: {
      headline: 'What are you looking for?',
      placeholder: 'Search for a product...',
      voice: 'Voice search',
      tags: ['Bags', 'Watches', 'Shoes', 'New'],
    },
    location: {
      caption: 'OUR STORES',
      headline: 'Find us near you',
      selectStore: 'Select your store to order',
      whatsapp: 'WhatsApp',
    },
    faq: {
      caption: 'FREQUENTLY ASKED QUESTIONS',
      headline: 'FAQ',
    },
    product: {
      inStock: 'In stock',
      outOfStock: 'Sold out',
      orderWhatsapp: 'Order on WhatsApp',      addToCart: 'Add to Cart',      addFavorites: 'Add to favorites',
      similar: 'Similar products',
      selectStore: 'Select store',
      yaounde: 'Yaoundé',
      kribi: 'Kribi',
    },
    cart: {
      title: 'Your cart',
      empty: 'Your cart is empty',
      discover: 'Discover products',
      subtotal: 'Subtotal',
      checkout: 'Checkout',
      continue: 'Continue shopping',
    },
    footer: {
      tagline: 'Elegance is priceless. Style has a price.',
      navigation: 'Navigation',
      contact: 'Contact',
      followUs: 'Follow us',
      rights: 'All rights reserved.',
      admin: 'Admin mode',
    },
    badges: {
      trending: 'Trending',
      new: 'New',
      premium: 'Premium',
      sold: 'Sold',
    },
    currency: 'FCFA',
  },
} as const;
